# Generated by Django 4.2.1 on 2023-06-19 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProductos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categorias',
        ),
        migrations.DeleteModel(
            name='CategoriaProd',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
