# Generated by Django 4.2.1 on 2023-06-18 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_detalle', models.IntegerField(verbose_name='Cantidad detalle')),
                ('subtotal_detalle', models.IntegerField(verbose_name='Subtotal detalle')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=50, verbose_name='Nombre producto')),
                ('descripcion_producto', models.CharField(max_length=150, verbose_name='Descripcion producto')),
                ('talla_producto', models.IntegerField(verbose_name='Talla de producto')),
                ('stock_producto', models.IntegerField(verbose_name='Stock producto')),
                ('precio_producto', models.IntegerField(verbose_name='Precio producto')),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='menu.detalle')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('rut_usuario', models.IntegerField(verbose_name='Ingrese su rut')),
                ('nombre_usuario', models.CharField(max_length=20, verbose_name='Ingrese su nombre')),
                ('apellido_usuario', models.CharField(max_length=20, verbose_name='Ingrese su apellido')),
                ('correo_usuario', models.EmailField(max_length=40, verbose_name='Ingrese su correo')),
                ('contraseña_usuario', models.CharField(max_length=40)),
                ('respuesta_usuario', models.CharField(default='default value', max_length=150, verbose_name='Respuesta')),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id_foto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='menu.producto')),
                ('nombre_foto', models.CharField(max_length=50, verbose_name='Nombre foto')),
                ('img_foto', models.ImageField(upload_to='', verbose_name='Imagen foto')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id_pregunta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='menu.usuario')),
                ('nombre_pregunta', models.CharField(max_length=100, verbose_name='Pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='menu.usuario')),
                ('nombre_rol', models.CharField(max_length=50, verbose_name='Nombre Rol')),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_modelo', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='menu.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_marca', models.CharField(max_length=50, verbose_name='Nombre marca')),
                ('id_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcas', to='menu.modelo')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('f_compra', models.DateField(verbose_name='Fecha de compra')),
                ('f_retiro', models.DateField(verbose_name='Fecha retiro')),
                ('estado_compra', models.CharField(max_length=40, verbose_name='Estado de la compra')),
                ('total', models.IntegerField(verbose_name='Total de la compra')),
                ('carrito_compra', models.CharField(max_length=100)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='menu.detalle')),
            ],
        ),
    ]
